# Generated by Django 5.1.7 on 2025-04-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_number", models.CharField(max_length=50)),
                ("delivery_item", models.CharField(max_length=200)),
                ("material", models.CharField(max_length=100)),
                ("material_text", models.TextField()),
                ("delivered_qty", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivered_qty_unit", models.CharField(max_length=50)),
                (
                    "price_unit_no_dph",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("price_unit_currency", models.CharField(max_length=10)),
                ("delivery_item_created_on", models.DateField()),
                ("delivery_item_created_at", models.DateTimeField()),
                ("delivery_item_created_by", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
