# Generated by Django 5.1.7 on 2025-04-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_delivery_delete_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivered_qty",
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivered_qty_unit",
            field=models.CharField(default="KS", max_length=2),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivery_item_created_by",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="material",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="material_text",
            field=models.CharField(max_length=40),
        ),
    ]
