# Generated by Django 5.1.7 on 2025-04-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_delivery_delivered_qty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="delivery_item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_number", models.CharField(max_length=50)),
                ("delivery_item", models.CharField(max_length=200)),
                ("material", models.CharField(max_length=5)),
                ("material_text", models.CharField(max_length=40)),
                ("delivered_qty", models.IntegerField()),
                ("delivered_qty_unit", models.CharField(default="KS", max_length=2)),
                (
                    "price_unit_no_dph",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("price_unit_currency", models.CharField(default="CZK", max_length=10)),
                ("delivery_item_created_on", models.DateField()),
                ("delivery_item_created_at", models.DateTimeField()),
                ("delivery_item_created_by", models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name="delivery",
        ),
    ]
