# Generated by Django 5.1.7 on 2025-04-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_delivery_item_delete_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery_item",
            name="delivery_item_created_at",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="delivery_item",
            name="delivery_item_created_on",
            field=models.CharField(max_length=20),
        ),
    ]
