# Generated by Django 5.1.7 on 2025-04-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_delivery_item_delivery_item_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="delivery_header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_number", models.CharField(max_length=20, unique=True)),
                ("delivery_type", models.CharField(max_length=2)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("invoice_currency", models.CharField(max_length=20)),
                ("due_date_invoice", models.CharField(max_length=20)),
                ("customer", models.CharField(max_length=30)),
                ("delivery_date", models.CharField(max_length=20)),
                ("delivery_created_on", models.CharField(max_length=20)),
                ("delivery_created_at", models.CharField(max_length=20)),
                ("delivery_created_by", models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name="delivery_item",
            name="delivery_item",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="delivery_item",
            name="delivery_number",
            field=models.CharField(max_length=20),
        ),
    ]
