# Generated by Django 5.1.7 on 2025-04-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_delivery_header_alter_delivery_item_delivery_item_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_code", models.CharField(max_length=5, unique=True)),
                ("customer_text", models.CharField(max_length=60)),
                ("customer_ico", models.CharField(max_length=20)),
                ("customer_street", models.CharField(max_length=128)),
                ("customer_cp", models.CharField(max_length=20)),
                ("customer_zip", models.CharField(max_length=10)),
                ("customer_city", models.CharField(max_length=60)),
                ("customer_email", models.CharField(max_length=60)),
                ("customer_phone", models.CharField(max_length=30)),
            ],
        ),
    ]
