# Generated by Django 5.1.7 on 2025-04-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_customers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery_header",
            name="delivery_number",
            field=models.CharField(max_length=20),
        ),
    ]
