# Generated by Django 5.0.14 on 2025-04-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_customers_customer_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery_header",
            name="delivery_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="delivery_header",
            name="invoice_currency",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="delivery_header",
            name="invoice_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="delivery_item",
            name="delivery_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="delivery_item",
            name="price_unit_currency",
            field=models.CharField(default="CZK", max_length=6),
        ),
    ]
