# Generated by Django 5.2 on 2025-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_delivery_header_delivery_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery_header",
            name="delivery_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="delivery_header",
            name="invoice_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="delivery_item",
            name="delivery_number",
            field=models.CharField(max_length=20),
        ),
    ]
