# Generated by Django 5.0.14 on 2025-04-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_delivery_header_delivery_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="customers",
        ),
        migrations.DeleteModel(
            name="delivery_header",
        ),
        migrations.DeleteModel(
            name="delivery_item",
        ),
    ]
