# Generated by Django 5.0.14 on 2025-04-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myapp", "0012_delete_customers_delete_delivery_header_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_code", models.CharField(max_length=5)),
                ("customer_text", models.CharField(max_length=60)),
                ("customer_ico", models.CharField(max_length=20)),
                ("customer_street", models.CharField(max_length=128)),
                ("customer_cp", models.CharField(max_length=20)),
                ("customer_zip", models.CharField(max_length=10)),
                ("customer_city", models.CharField(max_length=60)),
                ("customer_email", models.CharField(max_length=60)),
                ("customer_phone", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_number", models.CharField(max_length=20)),
                ("delivery_type", models.CharField(max_length=2)),
                ("invoice_number", models.IntegerField(default=0)),
                ("invoice_currency", models.CharField(max_length=6)),
                ("due_date_invoice", models.CharField(max_length=20)),
                ("customer", models.CharField(max_length=30)),
                ("delivery_date", models.CharField(max_length=20)),
                ("delivery_created_on", models.CharField(max_length=20)),
                ("delivery_created_at", models.CharField(max_length=20)),
                ("delivery_created_by", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_number", models.CharField(max_length=20)),
                ("delivery_item", models.CharField(max_length=4)),
                ("material", models.CharField(max_length=5)),
                ("material_text", models.CharField(max_length=40)),
                ("delivered_qty", models.IntegerField()),
                ("delivered_qty_unit", models.CharField(default="KS", max_length=2)),
                (
                    "price_unit_no_dph",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("price_unit_currency", models.CharField(default="CZK", max_length=6)),
                ("delivery_item_created_on", models.CharField(max_length=20)),
                ("delivery_item_created_at", models.CharField(max_length=20)),
                ("delivery_item_created_by", models.CharField(max_length=12)),
            ],
        ),
    ]
