# Generated by Django 5.2 on 2025-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryheader",
            name="customer",
        ),
        migrations.AddField(
            model_name="deliveryheader",
            name="customer_code",
            field=models.CharField(default="DEFAULT_CODE", max_length=5),
        ),
        migrations.AlterField(
            model_name="customers",
            name="customer_code",
            field=models.CharField(default="DEFAULT_CODE", max_length=5),
        ),
    ]
