# Generated by Django 5.2 on 2025-04-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_remove_deliveryheader_customer_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeliveryHeader",
        ),
    ]
