# Generated by Django 5.2 on 2025-04-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_delete_deliveryheader"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_number", models.CharField(max_length=20)),
                ("delivery_type", models.CharField(max_length=2)),
                ("invoice_number", models.IntegerField(default=0)),
                ("invoice_currency", models.CharField(max_length=6)),
                ("due_date_invoice", models.CharField(max_length=20)),
                (
                    "customer_code",
                    models.CharField(default="DEFAULT_CODE", max_length=5),
                ),
                ("delivery_date", models.CharField(max_length=20)),
                ("delivery_created_on", models.CharField(max_length=20)),
                ("delivery_created_at", models.CharField(max_length=20)),
                ("delivery_created_by", models.CharField(max_length=12)),
            ],
        ),
    ]
