# Generated by Django 5.2 on 2025-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_deliveryheader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="customer_code",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="deliveryheader",
            name="customer_code",
            field=models.CharField(max_length=5),
        ),
    ]
